#%RAML 1.0 DataType
type: object
properties:
  storeNumber:
    type: integer | nil
    required: false
  streamNumber:
    type: integer | nil
    required: false
  deliveryStreamName:
    type: string | nil
    required: false
  schemaName:
    type: string | nil
    required: false
  startFillDateTime:
    type: string | nil
    required: false
  deliveryDateTime:
    type: string | nil
    required: false
  fillDateTime:
    type: string | nil
    required: false
  orderDateTime:
    type: string | nil
    required: false
  initialPromotionFlag:
    type: string | nil
    required: false
  mainDeliveryFlag:
    type: string | nil
    required: false
  boxSize:
    type: integer | nil
    required: false
  storeAdviseFlag:
    type: string | nil
    required: false
  orderStatus:
    type: string | nil
    required: false
  totalInitialOrderQuantity:
    type: string | nil
    required: false
  totalOrderQuantity:
    type: string | nil
    required: false
  deliveryScheamaType:
    type: integer | nil
    required: false
  delivererNumber: 
    type: integer | nil
    required: false
  createdBy:
    type: string | nil
    required: false
  creationDateTime:
    type: string | nil
    required: false
  updatedBy:
    type: string | nil
    required: false
  updateDateTime:
    type: string | nil
    required: false
